### ISSUE TITLE
IGBP-CB_SingelPoint_error

### ISSUE THREAD

**Issue by tt2002-del** [CoLM-SYSU/CoLM202X#330]
服务器：land02
编译环境：intel
问题：在运行./colm.x时会产生以下报错
forrtl: severe (194): Run-Time Check Failure. The variable 'mod_vars_timevariables_mp_save_to_restart_$RWRITE' is being used in 'main/MOD_Vars_TimeVariables.F90(886,11)' without being defined
Image              PC                Routine            Line        Source
colm.x             000000000085C7DC  MAIN__                    518  CoLM.F90
colm.x             000000000040E5FD  Unknown               Unknown  Unknown
libc-2.31.so       00007F22FCBBA083  __libc_start_main     Unknown  Unknown
colm.x             000000000040E51E  Unknown               Unknown  Unknown

define.h如下
! 1. Spatial structure:
!    Select one of the following options.
#undef GRIDBASED
#undef CATCHMENT
#undef UNSTRUCTURED
#define SinglePoint

! 2. Land subgrid type classification:
!    Select one of the following options.
#undef LULC_USGS
#define LULC_IGBP
#undef LULC_IGBP_PFT
#undef LULC_IGBP_PC

! 2.1 3D Urban model (put it temporarily here):
#undef URBAN_MODEL

! 3. If defined, debug information is output.
#define CoLMDEBUG
! 3.1 If defined, range of variables is checked.
#define RangeCheck
! 3.1 If defined, surface data in vector is mapped to gridded data for checking.
#undef SrfdataDiag

! 4. If defined, MPI parallelization is enabled.
#undef USEMPI
!    Conflict: not used when defined SingPoint.
#if (defined SinglePoint)
#undef USEMPI
#endif

! 5. Hydrological process options.
! 5.1 Two soil hydraulic models can be used.
#define   Campbell_SOIL_MODEL
#undef  vanGenuchten_Mualem_SOIL_MODEL
! 5.2 If defined, lateral flow is modeled.
#define CatchLateralFlow
!    Conflicts :
#ifndef CATCHMENT
#undef CatchLateralFlow
#endif

! 6. If defined, CaMa-Flood model will be used.
#undef CaMa_Flood

! 7. If defined, BGC model is used.
#undef BGC

!    Conflicts :  only used when LULC_IGBP_PFT is defined.
#ifndef LULC_IGBP_PFT
#undef BGC
#endif
! 7.1 If defined, CROP model is used
#define CROP
!    Conflicts : only used when BGC is defined
#ifndef BGC
#undef CROP
#endif

! 8. If defined, open Land use and land cover change mode.
#undef LULCC

! 9. If defined, data assimilation is used.
#undef DataAssimilation

! 10. Vector write model.
!     1) "VectorInOneFileP" : write vector data in one file in parallel mode;  
!     2) "VectorInOneFileS" : write vector data in one file in serial mode;  
!     3) Neither "VectorInOneFileS" nor "VectorInOneFileP" is defined : 
!        write vector data in separate files.  
#undef VectorInOneFileP
!     Conflict
#ifdef VectorInOneFileP
#undef VectorInOneFileS
#endif

#undef USESplitAI

namelist信息如下
&nl_colm

! Author: Shupeng Zhang 
! Description : an example for SinglePoint with all surface data from database instead of observations.

   DEF_CASE_NAME = 'test1'
   
   SITE_lon_location = 102.17
   SITE_lat_location = 33.9

   USE_SITE_landtype         = .false.
   USE_SITE_pctpfts          = .false.
   USE_SITE_pctcrop          = .false.
   USE_SITE_htop             = .false.
   USE_SITE_LAI              = .false.
   USE_SITE_lakedepth        = .false.
   USE_SITE_soilreflectance  = .false.
   USE_SITE_soilparameters   = .false.
   USE_SITE_dbedrock         = .false.
   USE_SITE_topography       = .false.
   USE_SITE_urban_paras      = .false.

   DEF_simulation_time%greenwich    = .TRUE.
   DEF_simulation_time%start_year   = 2012
   DEF_simulation_time%start_month  = 1
   DEF_simulation_time%start_day    = 1
   DEF_simulation_time%start_sec    = 0
   DEF_simulation_time%end_year     = 2012
   DEF_simulation_time%end_month    = 12
   DEF_simulation_time%end_day      = 31
   DEF_simulation_time%end_sec      = 86400
   DEF_simulation_time%spinup_year  = 2012
   DEF_simulation_time%spinup_month = 1
   DEF_simulation_time%spinup_day   = 10
   DEF_simulation_time%spinup_sec   = 86400
   DEF_simulation_time%spinup_repeat = 1

   DEF_simulation_time%timestep     = 1800.

   DEF_dir_rawdata = '/shr03/CoLMrawdata/'
   DEF_dir_runtime = '/shr03/CoLMruntime/'
   DEF_dir_output  = '/stu02/taot24/cases/case1/'

   ! soil state init
   DEF_USE_SoilInit  = .true.
   DEF_file_SoilInit = '/tera13/zhangsp/landdata/soilstate/soilstate.nc' 

   ! LAI setting
   DEF_LAI_MONTHLY = .true.
   DEF_LAI_CHANGE_YEARLY = .false.

   ! ----- forcing -----
   ! Options :
   ! PRINCETON | GSWP3   | QIAN  | CRUNCEPV4 | CRUNCEPV7 | ERA5LAND | ERA5  |  MSWX
   ! WFDE5     | CRUJRA  | WFDEI | JRA55     | GDAS      | CMFD     | POINT |  JRA3Q
   DEF_forcing_namelist = '/stu02/taot24/colm/run/forcing/ERA5LAND.nml'
   
   ! ----- history -----
   ! DEF_WRST_FREQ = 'MONTHLY' ! write restart file frequency: HOURLY/DAILY/MONTHLY/YEARLY
   DEF_HIST_FREQ = 'DAILY' ! write history file frequency: HOURLY/DAILY/MONTHLY/YEARLY
   DEF_HIST_groupby = 'MONTH' ! history in one file: DAY/MONTH/YEAR

   ! DEF_hist_vars_namelist = '/stu02/taot24/colm/run/history.nml'
   DEF_HIST_vars_out_default = .true.

/

**Comment by tt2002-del** [comment]
namelist文件里注释掉DEF_WRST_FREQ =‘ ’，在运行中rwrite没被定义，但是报错文件没能显示MOD_Vars_TimeVariables.F90中883行的报错信息，具体如下：
      CASE default
         write(*,*) 'Warning: Please USE one of TIMESTEP/HOURLY/DAILY/MONTHLY/YEARLY for restart frequency.'
      ENDSELECT

**Comment by zhangsp8** [comment]
确认为代码问题，已修改，感谢反馈。
