### ISSUE TITLE
USGS_VG single point test - error in mksrfdata

### ISSUE THREAD

**Issue by jellywzx** [CoLM-SYSU/CoLM202X#338]
1. define.h: /stu02/weizx24/classwork/CoLM202X_20241128/include/define.h
2. nml: /stu02/weizx24/classwork/CoLM202X_20241128/run/SiteSYSUAtmos_IGBP_VG.nml
3. land02
4. Makeoptions.land.intel
5. mksrfdata报错，在/stu02/weizx24/classwork/CoLM202X_20241128/mksrfdata/MOD_LandPatch.F90中找不到landtype_usgs_update.nc（127行）
错误原因：正确的文件名应该是landtype-usgs-update.nc，下划线改小横线。
<img width="1081" alt="issue" src="https://github.com/user-attachments/assets/e70e69c9-0c76-4388-badc-edb3aaccb4a2">

**Comment by zhangsp8** [comment]
已修改，感谢反馈。
