### ISSUE TITLE
Error in MOD_landpatch.F90

### ISSUE THREAD

**Issue by Oscarrrhhhh** [CoLM-SYSU/CoLM202X#84]
In mksrfdata/MOD_landpatch.F90, Line 308to 317.

The "END IF" in 314 is falsely placed. It should be placed after calling landpatch%pset_pack.
This error could be triggered when one worker got no patches on it.

![image](https://github.com/CoLM-SYSU/CoLM202X/assets/28278836/591e25da-c0ae-4a11-aedf-c58e35eaf653)

**Comment by CoLM-SYSU** [comment]
Solved by zhangsp in PR#85
